const app=document.getElementById('app');
const KEY='resonance-game-v1';
let game=null;
let installPrompt=null;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved&&saved.version===1&&Array.isArray(saved.teams)&&saved.teams.length===2&&saved.teams.every(t=>typeof t.name==='string'&&Number.isFinite(t.score))&&Number.isInteger(saved.round)&&((saved.mode==='duo'&&saved.total===null)||([6,10,14].includes(saved.total)&&saved.round<=saved.total))&&saved.round>=1&&['handoff','host','guess','result','finish'].includes(saved.phase)&&Number.isFinite(saved.target)&&saved.target>=16&&saved.target<=84&&Number.isFinite(saved.guess)&&saved.guess>=0&&saved.guess<=100&&Array.isArray(saved.pair)&&saved.pair.length===2&&saved.pair.every(p=>typeof p==='string')&&typeof saved.clue==='string')game=saved;}catch{}
function save(){try{localStorage.setItem(KEY,JSON.stringify(game));}catch{}}
function clear(){game=null;try{localStorage.removeItem(KEY);}catch{}}
function show(html){app.innerHTML=html;app.style.animation='none';requestAnimationFrame(()=>app.style.animation='');window.scrollTo(0,0);}
function on(id,fn){document.getElementById(id)?.addEventListener('click',fn);}
function modal(html,button='Понятно'){document.getElementById('dialog-body').innerHTML=html;document.getElementById('close-dialog').textContent=button;document.getElementById('dialog').showModal();}
on('close-dialog',()=>document.getElementById('dialog').close());
on('help',()=>modal(`<div class="eyebrow">Как играть</div><h2>Поймайте мысль<br>друг друга.</h2><ol><li>Ведущий видит скрытую цель между двумя противоположностями. Остальные в это время не смотрят на экран.</li><li>Ведущий придумывает ассоциацию, соответствующую положению цели. Например, между «Холодное» и «Горячее»: «Чай, который забыли на столе».</li><li>Нажмите «Скрыть цель» и передайте телефон команде. Обсудите подсказку и передвиньте стрелку.</li><li>Откройте цель: центр приносит 4 очка, соседние зоны — 3 и 2. За пределами зон — 0.</li><li>Команды играют по очереди. Внутри команды меняйте ведущего каждый ход. После всех раундов побеждает команда с большим счётом.</li></ol><p><strong>Вдвоём:</strong> выберите режим «Вдвоём · просто на интерес». Один даёт подсказку, второй угадывает, затем роли меняются. Общего счёта и лимита раундов нет.</p><p>Не называйте числа, проценты или положение на шкале. Подсказка — одна идея, а не инструкция к стрелке.</p>`));
on('home',e=>{e.preventDefault();home();});
function point(value,r=145){const a=Math.PI*(1-value/100);return [180+Math.cos(a)*r,180-Math.sin(a)*r];}
function wedge(lo,hi,color){const a=point(Math.max(0,lo)),b=point(Math.min(100,hi));return `<path d="M180 180 L${a[0]} ${a[1]} A145 145 0 0 1 ${b[0]} ${b[1]} Z" fill="${color}"/>`;}
function needle(value,color,id=''){const p=point(value,132);return `<line ${id?`id="${id}"`:''} x1="180" y1="180" x2="${p[0]}" y2="${p[1]}" stroke="${color}" stroke-width="5" stroke-linecap="round"/>`;}
function dial({target=null,guess=50,reveal=false,hero=false}={}){let ticks='';for(let i=0;i<=100;i+=5){const p=point(i,153),q=point(i,i%25===0?165:160);ticks+=`<line x1="${p[0]}" y1="${p[1]}" x2="${q[0]}" y2="${q[1]}" stroke="#adbfbb" opacity=".5" stroke-width="1.5"/>`;}
return `<div class="dial-wrap"><svg class="dial" viewBox="0 0 360 208" role="img" aria-label="${target!==null?'Шкала с открытой целью':'Шкала от одной противоположности до другой'}"><defs><linearGradient id="dialGradient"><stop stop-color="#c9dcc5"/><stop offset="1" stop-color="#e8a45c"/></linearGradient></defs><path d="M35 180 A145 145 0 0 1 325 180 Z" fill="${hero?'url(#dialGradient)':'#ebeadb'}"/>${target!==null?wedge(target-16,target+16,'#e4bd80')+wedge(target-10,target+10,'#d98c52')+wedge(target-4,target+4,'#b95138'):''}${ticks}${target!==null?needle(target,'#843c2c'):''}${target===null||reveal?needle(guess,'#142c31','guess-needle'):''}<circle cx="180" cy="180" r="14" fill="#142c31"/><circle cx="180" cy="180" r="5" fill="#e8a45c"/><path d="M24 180H336" stroke="#142c31" stroke-width="3"/>${target!==null?`<text x="${point(target,105)[0]}" y="${point(target,105)[1]}" text-anchor="middle" fill="#fff4df" font-size="13" font-weight="700">4</text>`:''}</svg></div>`;}
function home(){show(`<div class="eyebrow">Игра для тех, кто понимает друг друга</div><h1>Поймай<br>одну волну.</h1><p>Одна подсказка. Две противоположности.<br>Насколько близко вы мыслите?</p><div class="hero-art">${dial({guess:67,hero:true})}</div><div class="art-caption">МЕЖДУ «ПОЧТИ» И «ТОЧНО»</div>${game?'<button id="resume" class="button primary">Продолжить игру</button>':''}<button id="new" class="button ${game?'secondary':'primary'}">${game?'Новая игра':'Собрать компанию'} <span aria-hidden="true">↗</span></button><button id="duo" class="button secondary">Вдвоём · просто на интерес</button><div class="features"><span>2–12 игроков</span><span>15–25 минут</span><span>Один телефон</span></div><button class="text-button" id="install">Как установить на Android</button>`);on('new',()=>setup());on('duo',()=>setupDuo());on('resume',()=>render());on('install',async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;return;}modal('<h2>Игра на вашем Pixel</h2><p>Откройте ссылку игры в Chrome. В меню ⋮ выберите «Добавить на главный экран» или «Установить приложение».</p><p>Для установки с автономной работой нужна HTTPS-ссылка. На адресе локальной сети игра работает в браузере; установка и офлайн-режим могут быть недоступны.</p>');});}
function setup(){show(`<div class="eyebrow">Перед стартом</div><h2>Кто сегодня<br>на одной волне?</h2><p>Разделитесь на две команды, минимум по два человека. Ведущие будут меняться.</p><form id="setup"><div class="card"><label class="field">Первая команда<input name="first" maxlength="24" value="Мандарин" required autocomplete="off"></label><label class="field">Вторая команда<input name="second" maxlength="24" value="Эвкалипт" required autocomplete="off"></label></div><div class="eyebrow">Количество раундов · на обе команды</div><div class="segmented" role="group" aria-label="Количество раундов"><button type="button" data-rounds="6">6 · Быстро</button><button type="button" data-rounds="10" class="selected" aria-pressed="true">10 · Классика</button><button type="button" data-rounds="14">14 · Подольше</button></div><p class="hint">У каждой команды будет одинаковое число ходов.<br>Все видят экран, кроме момента выбора подсказки.</p><button class="button primary" type="submit">Поехали <span aria-hidden="true">→</span></button></form>`);let total=10;document.querySelectorAll('[data-rounds]').forEach(b=>{b.setAttribute('aria-pressed',String(Number(b.dataset.rounds)===total));b.onclick=()=>{total=Number(b.dataset.rounds);document.querySelectorAll('[data-rounds]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});};});document.getElementById('setup').onsubmit=e=>{e.preventDefault();const data=new FormData(e.target);game={version:1,teams:[{name:String(data.get('first')).trim()||'Мандарин',score:0},{name:String(data.get('second')).trim()||'Эвкалипт',score:0}],round:1,total,phase:'handoff',deck:[],clue:'',guess:50};newRound();};}
function setupDuo(){show(`<div class="eyebrow">Вдвоём · без соревнования</div><h2>Просто понять<br>друг друга.</h2><p>Один придумывает подсказку, другой угадывает. После каждого раунда меняйтесь ролями. Без общего счёта и ограничения по раундам.</p><form id="duo-setup"><div class="card"><label class="field">Первый игрок<input name="first" maxlength="24" value="Игрок 1" required autocomplete="off"></label><label class="field">Второй игрок<input name="second" maxlength="24" value="Игрок 2" required autocomplete="off"></label></div><p class="hint">Попадание покажет, насколько близко вы мыслите.<br>Закончить можно после любого раунда.</p><button class="button primary" type="submit">Начать вдвоём →</button></form>`);document.getElementById('duo-setup').onsubmit=e=>{e.preventDefault();const data=new FormData(e.target);game={version:1,mode:'duo',teams:[{name:String(data.get('first')).trim()||'Игрок 1',score:0},{name:String(data.get('second')).trim()||'Игрок 2',score:0}],round:1,total:null,phase:'handoff',deck:[],clue:'',guess:50};newRound();};}
function isDuo(){return game?.mode==='duo';}
function newRound(){if(!Array.isArray(game.deck)||!game.deck.length){game.deck=Rules.pairs.map((_,i)=>i);for(let i=game.deck.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[game.deck[i],game.deck[j]]=[game.deck[j],game.deck[i]];}}game.pair=Rules.pairs[game.deck.pop()];game.target=Rules.target();game.guess=50;game.clue='';game.phase='handoff';save();render();}
function active(){return (game.round-1)%2;}
function roundHeader(){if(isDuo())return `<div class="roundbar"><span>РАУНД ${game.round}</span><span>ВДВОЁМ · БЕЗ СЧЁТА</span></div><div class="badge">Подсказка: ${escape(game.teams[active()].name)} · Угадывает: ${escape(game.teams[1-active()].name)}</div>`;return `<div class="roundbar"><span>РАУНД ${game.round} / ${game.total}</span><span>${game.phase==='finish'?'ИГРА ОКОНЧЕНА':'ХОД КОМАНДЫ '+(active()+1)}</span></div><div class="scoreboard">${game.teams.map((t,i)=>`<div class="team ${i===active()?'active':''}"><span>${escape(t.name)}</span><b>${t.score}</b></div>`).join('')}</div>`;}
function labels(){return `<div class="spectrum-labels"><span>← ${escape(game.pair[0])}</span><span>${escape(game.pair[1])} →</span></div>`;}
function render(){if(!game)return home();const phase=game.phase;
if(phase==='handoff'){show(roundHeader()+`<div class="badge">Только для ведущего</div><h2>Передайте телефон<br>ведущему.</h2><p>${isDuo()?`${escape(game.teams[active()].name)}, сейчас вы даёте подсказку. ${escape(game.teams[1-active()].name)}, отвернитесь, пока цель открыта.`:`Команда «${escape(game.teams[active()].name)}», выберите того, кто даст подсказку. Остальные отвернитесь — цель должна остаться секретом.`}</p><div class="privacy" aria-hidden="true">◉</div><button class="button primary" id="host">Я ведущий · показать цель</button><p class="hint">Цель откроется только после нажатия.</p>`);on('host',()=>{game.phase='host';save();render();});}
if(phase==='host'){show(roundHeader()+`<div class="badge">Секретный экран · только ведущий</div><h2>Придумайте<br>подсказку.</h2>${dial({target:game.target})}${labels()}<p class="hint">Красный сектор — центр цели на 4 очка.<br>Какая ассоциация подходит этому месту?</p><form id="clue-form"><label class="field">Ваша подсказка<input id="clue-input" maxlength="100" placeholder="Например: чай, забытый на столе" value="${escape(game.clue)}" required autocomplete="off"></label><button class="button primary">Скрыть цель и передать телефон</button></form><button id="reroll" class="text-button">Другая пара противоположностей</button>`);document.getElementById('clue-input').oninput=e=>{game.clue=e.target.value;save();};document.getElementById('clue-form').onsubmit=e=>{e.preventDefault();const clue=document.getElementById('clue-input').value.trim();if(!clue){document.getElementById('clue-input').setCustomValidity('Введите подсказку');document.getElementById('clue-input').reportValidity();return;}game.clue=clue;game.phase='guess';save();render();};document.getElementById('clue-input').addEventListener('input',e=>e.target.setCustomValidity(''));on('reroll',()=>{newRound();game.phase='host';save();render();});}
if(phase==='guess'){show(roundHeader()+`<div class="eyebrow">${isDuo()?`${escape(game.teams[1-active()].name)}, ваш ход`:'Обсуждайте всей командой'}</div><h2>Где спрятана<br>эта мысль?</h2><div class="clue"><small>ПОДСКАЗКА ВЕДУЩЕГО</small><strong>${escape(game.clue)}</strong></div>${dial({guess:game.guess})}${labels()}<input id="guess" type="range" min="0" max="100" step="1" value="${game.guess}" aria-label="Положение стрелки между противоположностями"><div class="range-label"><span>Ближе к левому</span><span>Ближе к правому</span></div><p class="hint">${isDuo()?'Двигайте ползунок туда, куда подходит подсказка.':'Двигайте ползунок, пока команда не договорится.'}<br>Ведущий сохраняет молчание.</p><button id="reveal" class="button primary">Открыть цель</button>`);document.getElementById('guess').oninput=e=>{game.guess=Number(e.target.value);const p=point(game.guess,132),n=document.getElementById('guess-needle');n.setAttribute('x2',p[0]);n.setAttribute('y2',p[1]);save();};on('reveal',()=>{game.points=Rules.score(game.target,game.guess);if(!isDuo())game.teams[active()].score+=game.points;game.phase='result';save();navigator.vibrate?.(game.points? [40,50,40]:30);render();});}
if(phase==='result'){const points=Rules.score(game.target,game.guess);show(roundHeader()+`<div class="center"><div class="result-number">${isDuo()?points+'/4':'+'+points}<span>${isDuo()?'попадание':points===0?'очков':points===2||points===3||points===4?'очка':'очко'}</span></div><h2 class="result-title">${points===4?'На одной волне!':points===3?'Очень близко!':points===2?'Есть контакт!':'Мысль была чуть дальше.'}</h2><p>${points?'Хорошее попадание. Обсудите, как вы это поняли.':'Расскажите друг другу, почему выбрали это место.'}</p></div>${dial({target:game.target,guess:game.guess,reveal:true})}${labels()}<div class="legend"><span><i style="background:#b95138"></i>Цель</span><span><i style="background:#f3eee0"></i>Чёрная стрелка — ваш ответ</span></div><div class="clue"><small>ВАША ПОДСКАЗКА</small><strong>${escape(game.clue)}</strong></div><button class="button primary" id="next">${isDuo()?'Поменяться ролями →':game.round===game.total?'Итоги игры':'Следующая команда →'}</button>${isDuo()?'<button class="text-button" id="end-duo">Закончить игру</button>':''}`);on('end-duo',()=>{clear();home();});on('next',()=>{if(!isDuo()&&game.round===game.total){game.phase='finish';save();render();}else{game.round++;newRound();}});}
if(phase==='finish'){const a=game.teams[0],b=game.teams[1],tie=a.score===b.score,winner=a.score>b.score?a:b;show(`<div class="eyebrow">Все ${game.total} раундов сыграны</div><h1>${tie?'Одна волна.<br>Две команды.':'Поймали<br>свою волну.'}</h1><div class="privacy" aria-hidden="true">≈</div><div class="center"><div class="badge">${tie?'Ничья':'Победители'}</div><h2>${tie?'Победила дружба':escape(winner.name)}</h2><p>${tie?'Вы понимаете друг друга одинаково хорошо.':'Ассоциации совпали. Осталось отпраздновать.'}</p></div><div class="scoreboard">${game.teams.map(t=>`<div class="team"><span>${escape(t.name)}</span><b>${t.score}</b></div>`).join('')}</div><button class="button primary" id="again">Ещё одну игру</button><button class="button secondary" id="end">На главный экран</button>`);on('again',()=>setup());on('end',()=>{clear();home();});}}
// A returning screen never exposes the host's target without an explicit tap.
document.addEventListener('visibilitychange',()=>{if(document.hidden&&game?.phase==='host'){game.phase='handoff';save();render();}});
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;});
if('serviceWorker'in navigator&&window.isSecureContext){navigator.serviceWorker.register('./sw.js').catch(()=>{});}
if(game?.phase==='host'){game.phase='handoff';save();}
home();
