const app=document.getElementById('app');
const KEY='resonance-game-v2';
let game=null,installPrompt=null;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
try{const s=JSON.parse(localStorage.getItem(KEY));if(s&&s.version===2&&['duo','group'].includes(s.mode)&&Array.isArray(s.teams)&&s.teams.length>=2&&s.teams.length<=6&&s.teams.every(t=>typeof t.name==='string'&&Number.isFinite(t.score)&&Number.isInteger(t.turns))&&Number.isInteger(s.round)&&s.round>=1&&(s.total===null||[6,10,14].includes(s.total))&&['handoff','host','pass','guess','ready','result','finish'].includes(s.phase)&&Array.isArray(s.answers)&&Number.isFinite(s.target)&&Array.isArray(s.pair)&&Array.isArray(s.results)&&Number.isInteger(s.completed))game=s;}catch{}
function save(){try{localStorage.setItem(KEY,JSON.stringify(game));}catch{}}
function clear(){game=null;try{localStorage.removeItem(KEY);}catch{}}
function show(html){app.innerHTML=html;app.style.animation='none';requestAnimationFrame(()=>app.style.animation='');window.scrollTo(0,0);}
function on(id,fn){document.getElementById(id)?.addEventListener('click',fn);}
function modal(html){document.getElementById('dialog-body').innerHTML=html;document.getElementById('close-dialog').textContent='Понятно';document.getElementById('dialog').showModal();}
function isDuo(){return game?.mode==='duo';}
function hostIndex(){return (game.round-1)%2;}
function guessIndex(){return isDuo()?1-hostIndex():game.cursor;}
function finish(){game.phase='finish';save();render();}
function endButton(){return '<button class="text-button" id="finish-early">Завершить игру · показать итоги</button>';}
function bindEnd(){on('finish-early',finish);}
on('close-dialog',()=>document.getElementById('dialog').close());
on('home',e=>{e.preventDefault();if(game?.phase==='host'){game.phase='handoff';save();}home();});
on('help',()=>modal('<div class="eyebrow">Как играть</div><h2>Поймайте мысль друг друга.</h2><ol><li>Ведущий открывает секретную цель и придумывает одну подсказку. Другие игроки не смотрят на экран.</li><li>В группе ведущий — отдельный участник, который не угадывает. Все команды угадывают одну и ту же подсказку по очереди.</li><li>Каждая команда выставляет стрелку, сохраняет ответ и передаёт телефон следующей. Чужие ответы не показываются. Цель открывается только после ответов всех команд.</li><li>После открытия каждая команда получает свои очки: 4 за центр, 3 и 2 за соседние зоны, 0 за промах.</li><li>Вдвоём ведущий и угадывающий меняются каждый раунд. Очки получает только угадывающий игрок.</li></ol><p>Можно выбрать 6, 10, 14 раундов или играть вдвоём без ограничения. При досрочном завершении итоги показывают очки за уже открытые раунды. Незавершённый раунд не засчитывается.</p><p>Не называйте числа, проценты или положение на шкале.</p>'));
function point(value,r=145){const a=Math.PI*(1-value/100);return [180+Math.cos(a)*r,180-Math.sin(a)*r];}
function wedge(lo,hi,color){const a=point(Math.max(0,lo)),b=point(Math.min(100,hi));return `<path d="M180 180 L${a[0]} ${a[1]} A145 145 0 0 1 ${b[0]} ${b[1]} Z" fill="${color}"/>`;}
function needle(value,color,id=''){const p=point(value,132);return `<line ${id?`id="${id}"`:''} x1="180" y1="180" x2="${p[0]}" y2="${p[1]}" stroke="${color}" stroke-width="5" stroke-linecap="round"/>`;}
function dial({target=null,guess=50,reveal=false,hero=false}={}){let ticks='';for(let i=0;i<=100;i+=5){const p=point(i,153),q=point(i,i%25===0?165:160);ticks+=`<line x1="${p[0]}" y1="${p[1]}" x2="${q[0]}" y2="${q[1]}" stroke="#adbfbb" opacity=".5" stroke-width="1.5"/>`;}
return `<div class="dial-wrap"><svg class="dial" viewBox="0 0 360 208" role="img" aria-label="${target!==null?'Шкала с открытой целью':'Шкала от одной противоположности до другой'}"><defs><linearGradient id="dialGradient"><stop stop-color="#c9dcc5"/><stop offset="1" stop-color="#e8a45c"/></linearGradient></defs><path d="M35 180 A145 145 0 0 1 325 180 Z" fill="${hero?'url(#dialGradient)':'#ebeadb'}"/>${target!==null?wedge(target-16,target+16,'#e4bd80')+wedge(target-10,target+10,'#d98c52')+wedge(target-4,target+4,'#b95138'):''}${ticks}${target!==null?needle(target,'#843c2c'):''}${target===null||reveal?needle(guess,'#142c31','guess-needle'):''}<circle cx="180" cy="180" r="14" fill="#142c31"/><circle cx="180" cy="180" r="5" fill="#e8a45c"/><path d="M24 180H336" stroke="#142c31" stroke-width="3"/>${target!==null?`<text x="${point(target,105)[0]}" y="${point(target,105)[1]}" text-anchor="middle" fill="#fff4df" font-size="13" font-weight="700">4</text>`:''}</svg></div>`;}
function home(){show(`<div class="eyebrow">Игра для тех, кто понимает друг друга</div><h1>Поймай<br>одну волну.</h1><p>Одна подсказка. Две противоположности.<br>Насколько близко вы мыслите?</p><div class="hero-art">${dial({guess:67,hero:true})}</div><div class="art-caption">МЕЖДУ «ПОЧТИ» И «ТОЧНО»</div>${game?'<button id="resume" class="button primary">Продолжить игру</button>':''}<button id="new" class="button ${game?'secondary':'primary'}">${game?'Новая игра в компании':'Собрать компанию'} ↗</button><button id="duo" class="button secondary">Вдвоём · просто на интерес</button><div class="features"><span>2–6 команд или вдвоём</span><span>Один телефон</span></div><button class="text-button" id="install">Как установить на Android</button>`);on('new',()=>setup('group'));on('duo',()=>setup('duo'));on('resume',render);on('install',async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;return;}modal('<h2>Игра на вашем Pixel</h2><p>Откройте HTTPS-ссылку игры в Chrome. В меню ⋮ выберите «Добавить на главный экран» или «Установить приложение».</p>');});}
function setup(mode){const duo=mode==='duo';show(`<div class="eyebrow">${duo?'Вдвоём · с личными очками':'Компания · одна подсказка для всех'}</div><h2>${duo?'Понять друг<br>друга.':'Каждая команда<br>на своей волне.'}</h2><p>${duo?'Один даёт подсказку, другой угадывает и получает очки. Затем роли меняются.':'Выберите отдельного ведущего. Он даёт общую подсказку, а все команды по очереди сохраняют свои ответы. После этого цель открывается для всех.'}</p><form id="setup">${duo?'':`<label class="field">Количество команд<select id="team-count">${[2,3,4,5,6].map(n=>`<option value="${n}">${n}</option>`).join('')}</select></label>`}<div class="card" id="names"></div><div class="eyebrow">Количество раундов${duo?' · роли чередуются':' · все команды в каждом'}</div><div class="segmented" role="group" aria-label="Количество раундов">${[6,10,14,...(duo?[0]:[])].map(n=>`<button type="button" data-rounds="${n}" aria-pressed="${n===(duo?0:10)}" class="${n===(duo?0:10)?'selected':''}">${n||'Без лимита'}</button>`).join('')}</div><p class="hint">${duo?'Очки начисляются угадывающему игроку.':'Ответы других команд скрыты до открытия цели.'}<br>Завершить с итогами можно в любой момент.</p><button class="button primary" type="submit">${duo?'Начать вдвоём':'Поехали'} →</button></form>`);
const names=document.getElementById('names');let count=2,total=duo?null:10;const values=duo?['Игрок 1','Игрок 2']:['Мандарин','Эвкалипт','Лаванда','Корица','Мята','Имбирь'];function drawNames(){names.innerHTML=Array.from({length:count},(_,i)=>`<label class="field">${duo?'Игрок':'Команда'} ${i+1}<input name="name-${i}" maxlength="24" value="${escape(values[i])}" required autocomplete="off"></label>`).join('');names.querySelectorAll('input').forEach((input,i)=>input.oninput=()=>values[i]=input.value);}
drawNames();if(!duo)document.getElementById('team-count').onchange=e=>{count=Number(e.target.value);drawNames();};document.querySelectorAll('[data-rounds]').forEach(b=>b.onclick=()=>{total=Number(b.dataset.rounds)||null;document.querySelectorAll('[data-rounds]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});});document.getElementById('setup').onsubmit=e=>{e.preventDefault();game={version:2,mode,teams:values.slice(0,count).map((name,i)=>({name:name.trim()||`${duo?'Игрок':'Команда'} ${i+1}`,score:0,turns:0})),round:1,total,completed:0,deck:[]};newRound();};}
function newRound(){if(!Array.isArray(game.deck)||!game.deck.length){game.deck=Rules.pairs.map((_,i)=>i);for(let i=game.deck.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[game.deck[i],game.deck[j]]=[game.deck[j],game.deck[i]];}}game.pair=Rules.pairs[game.deck.pop()];game.target=Rules.target();game.guess=50;game.clue='';game.cursor=0;game.answers=game.teams.map(()=>null);game.results=[];game.phase='handoff';save();render();}
function scoreboard(){return `<div class="scoreboard">${game.teams.map((t,i)=>`<div class="team ${['pass','guess'].includes(game.phase)&&i===guessIndex()?'active':''}"><span>${escape(t.name)}</span><b>${t.score}</b></div>`).join('')}</div>`;}
function roundHeader(){return `<div class="roundbar"><span>РАУНД ${game.round}${game.total?' / '+game.total:''}</span><span>${isDuo()?'ВДВОЁМ':'ВСЕ КОМАНДЫ'}</span></div>${scoreboard()}${isDuo()?`<div class="badge">Подсказка: ${escape(game.teams[hostIndex()].name)} · Угадывает: ${escape(game.teams[1-hostIndex()].name)}</div>`:''}`;}
function labels(){return `<div class="spectrum-labels"><span>← ${escape(game.pair[0])}</span><span>${escape(game.pair[1])} →</span></div>`;}
function reveal(){if(Rules.reveal(game)){save();navigator.vibrate?.(40);render();}}
function render(){if(!game)return home();const phase=game.phase;
if(phase==='handoff'){show(roundHeader()+`<div class="badge">Только для ведущего</div><h2>Передайте телефон<br>ведущему.</h2><p>${isDuo()?`${escape(game.teams[hostIndex()].name)}, сейчас вы даёте подсказку. ${escape(game.teams[1-hostIndex()].name)}, отвернитесь.`:'Ведущий не участвует в угадывании. Все команды отвернитесь: цель должна остаться секретом.'}</p><div class="privacy" aria-hidden="true">◉</div><button class="button primary" id="host">Я ведущий · показать цель</button>${endButton()}`);on('host',()=>{game.phase='host';save();render();});}
if(phase==='host'){show(roundHeader()+`<div class="badge">Секретный экран · только ведущий</div><h2>Придумайте<br>подсказку.</h2>${dial({target:game.target})}${labels()}<p class="hint">Красный сектор — центр цели на 4 очка.<br>Какая ассоциация подходит этому месту?</p><form id="clue-form"><label class="field">Ваша подсказка<input id="clue-input" maxlength="100" placeholder="Например: чай, забытый на столе" value="${escape(game.clue)}" required autocomplete="off"></label><button class="button primary">Скрыть цель и передать телефон</button></form><button id="reroll" class="text-button">Другая пара противоположностей</button>${endButton()}`);const input=document.getElementById('clue-input');input.oninput=()=>{input.setCustomValidity('');game.clue=input.value;save();};document.getElementById('clue-form').onsubmit=e=>{e.preventDefault();if(!input.value.trim()){input.setCustomValidity('Введите подсказку');input.reportValidity();return;}game.clue=input.value.trim();game.phase='pass';save();render();};on('reroll',()=>{newRound();game.phase='host';save();render();});}
if(phase==='pass'){show(roundHeader()+`<div class="eyebrow">${isDuo()?'Теперь угадывайте':`Ответ ${game.cursor+1} из ${game.teams.length}`}</div><h2>Телефон для<br>${escape(game.teams[guessIndex()].name)}.</h2><p>${isDuo()?'Ведущий сохраняет молчание.':'Обсудите общую подсказку и сохраните свою стрелку. Следующая команда получит чистую шкалу, без вашего ответа.'}</p><button class="button primary" id="start-guess">${isDuo()?'Я готов угадывать':'Наша команда готова'}</button>${endButton()}`);on('start-guess',()=>{game.phase='guess';save();render();});}
if(phase==='guess'){show(roundHeader()+`<div class="eyebrow">${escape(game.teams[guessIndex()].name)}, ваш ответ</div><h2>Где спрятана<br>эта мысль?</h2><div class="clue"><small>ПОДСКАЗКА ВЕДУЩЕГО</small><strong>${escape(game.clue)}</strong></div>${dial({guess:game.guess})}${labels()}<input id="guess" type="range" min="0" max="100" step="1" value="${game.guess}" aria-label="Положение стрелки между противоположностями"><div class="range-label"><span>Ближе к левому</span><span>Ближе к правому</span></div><p class="hint">${isDuo()?'Двигайте ползунок туда, куда подходит подсказка.':'Договоритесь внутри команды и сохраните ответ.'}<br>Ведущий сохраняет молчание.</p><button id="save-answer" class="button primary">${isDuo()?'Открыть цель':'Сохранить ответ'}</button>${endButton()}`);document.getElementById('guess').oninput=e=>{game.guess=Number(e.target.value);const p=point(game.guess,132),n=document.getElementById('guess-needle');n.setAttribute('x2',p[0]);n.setAttribute('y2',p[1]);save();};on('save-answer',()=>{game.answers[guessIndex()]=game.guess;if(isDuo()){game.phase='ready';reveal();}else if(game.cursor+1<game.teams.length){game.cursor++;game.guess=50;game.phase='pass';save();render();}else{game.phase='ready';save();render();}});}
if(phase==='ready'){show(roundHeader()+`<div class="eyebrow">Все ответы сохранены</div><h2>Откроем<br>общую цель?</h2><p>Каждая команда сделала свой выбор. Сейчас вы увидите все стрелки и очки за этот раунд.</p><div class="clue"><small>ОБЩАЯ ПОДСКАЗКА</small><strong>${escape(game.clue)}</strong></div><button id="reveal" class="button primary">Открыть цель для всех</button>${endButton()}`);on('reveal',reveal);}
if(phase==='result'){show(roundHeader()+`<div class="eyebrow">${isDuo()?'Очки угадывающего игрока':'Общая цель · отдельные результаты'}</div><h2>${isDuo()?'Поймали мысль?':'Вот как вы<br>её поняли.'}</h2><div class="clue"><small>ПОДСКАЗКА ВЕДУЩЕГО</small><strong>${escape(game.clue)}</strong></div>${game.results.map(r=>`<section class="card"><div class="result-row"><strong>${escape(game.teams[r.index].name)}</strong><b>+${r.points} ${r.points===0?'очков':'очка'}</b></div>${dial({target:game.target,guess:r.guess,reveal:true})}${labels()}<div class="hint">Красный сектор — цель · чёрная стрелка — ответ</div></section>`).join('')}<button class="button primary" id="next">${game.total&&game.round===game.total?'Итоги игры':isDuo()?'Поменяться ролями →':'Следующий раунд →'}</button>${endButton()}`);on('next',()=>{if(game.total&&game.round===game.total)finish();else{game.round++;newRound();}});}
if(phase==='finish'){const max=Math.max(...game.teams.map(t=>t.score)),winners=game.teams.filter(t=>t.score===max);show(`<div class="eyebrow">Итоги · завершено раундов: ${game.completed}</div><h1>Ваша общая<br>волна.</h1><p>${game.completed===0?'Вы завершили игру до открытия первой цели.':winners.length===game.teams.length?'Равный счёт!':`Больше всего очков: ${winners.map(t=>escape(t.name)).join(', ')}.`}</p><div class="card">${game.teams.map(t=>`<div class="result-row"><div><strong>${escape(t.name)}</strong><small>Ответов засчитано: ${t.turns}</small></div><b>${t.score} ${t.score%10===1&&t.score%100!==11?'очко':t.score%10>=2&&t.score%10<=4&&(t.score%100<12||t.score%100>14)?'очка':'очков'}</b></div>`).join('')}</div><p class="hint">Засчитаны только раунды, в которых была открыта цель.${isDuo()?' Игроки получают очки за свои угадывания.':''}</p><button class="button primary" id="again">Ещё одну игру</button><button class="button secondary" id="end">На главный экран</button>`);on('again',()=>setup(game.mode));on('end',()=>{clear();home();});}
bindEnd();}
document.addEventListener('visibilitychange',()=>{if(document.hidden&&game?.phase==='host'){game.phase='handoff';save();render();}});
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;});
if('serviceWorker'in navigator&&window.isSecureContext)navigator.serviceWorker.register('./sw.js').catch(()=>{});
if(game?.phase==='host'){game.phase='handoff';save();}
home();
