const test=require('node:test');
const assert=require('node:assert/strict');
const rules=require('../rules.js');
function session(mode,answers){return {mode,round:1,target:50,answers,phase:'ready',completed:0,teams:answers.map((_,i)=>({name:'Player '+i,score:0,turns:0}))};}
test('All teams earn their own points on a shared target, once only',()=>{const g=session('group',[50,40,34,0]);assert.equal(rules.reveal(g),true);assert.deepEqual(g.teams.map(t=>t.score),[4,3,2,0]);assert.deepEqual(g.teams.map(t=>t.turns),[1,1,1,1]);assert.equal(g.completed,1);assert.equal(rules.reveal(g),false);assert.deepEqual(g.teams.map(t=>t.score),[4,3,2,0]);});
test('No reveal or points before every team saves a valid answer',()=>{for(const answer of [null,undefined,-1,101,NaN]){const g=session('group',[50,answer]);assert.equal(rules.reveal(g),false);assert.equal(g.phase,'ready');assert.equal(g.completed,0);assert.deepEqual(g.teams.map(t=>t.score),[0,0]);}});
test('Duo points go to the guesser and alternate with roles',()=>{const g=session('duo',[null,50]);assert.equal(rules.reveal(g),true);assert.deepEqual(g.teams.map(t=>t.score),[0,4]);g.round=2;g.answers=[40,null];g.phase='ready';assert.equal(rules.reveal(g),true);assert.deepEqual(g.teams.map(t=>t.score),[3,4]);assert.deepEqual(g.teams.map(t=>t.turns),[1,1]);assert.equal(g.completed,2);});
test('Ending an incomplete round preserves the previous totals',()=>{const g=session('group',[50,40]);rules.reveal(g);g.answers=[50,null];g.phase='guess';assert.equal(rules.reveal(g),false);g.phase='finish';assert.equal(rules.reveal(g),false);assert.deepEqual(g.teams.map(t=>t.score),[4,3]);assert.equal(g.completed,1);});
test('Scoring boundaries are symmetric and inclusive',()=>{for(const direction of [-1,1]){for(const [distance,points] of [[0,4],[4,4],[5,3],[10,3],[11,2],[16,2],[17,0],[50,0]])assert.equal(rules.score(50,50+distance*direction),points);}});
test('Targets leave room for all scoring zones',()=>{assert.equal(rules.target(()=>0),16);assert.equal(rules.target(()=>.999999),84);for(let i=0;i<1000;i++){const target=rules.target();assert.ok(target>=16&&target<=84);assert.ok(Number.isInteger(target));}});
test('Deck contains sixty unique complete pairs',()=>{assert.equal(rules.pairs.length,60);assert.equal(new Set(rules.pairs.map(p=>p.join('|'))).size,60);assert.ok(rules.pairs.every(p=>p.length===2&&p.every(x=>typeof x==='string'&&x.length)));});
